services:
  web:
    build:
      context: ./convertit
      dockerfile: Dockerfile
    image: webapp:latest
    container_name: webapp
    ports:
      - "8000:8000"
    volumes:
      - ./convertit:/app
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
